"""add_spotify_playlist_id_to_playlists

Revision ID: 6b10ba2c0a55
Revises: 2dbc553385c5
Create Date: 2026-03-19 10:45:26.911465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b10ba2c0a55'
down_revision: Union[str, Sequence[str], None] = '2dbc553385c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_playlist_id', sa.String(length=22), nullable=True))
        batch_op.create_index(batch_op.f('ix_playlists_spotify_playlist_id'), ['spotify_playlist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlists_spotify_playlist_id'))
        batch_op.drop_column('spotify_playlist_id')

    # ### end Alembic commands ###
